#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Daily Evolution Script
Generate daily evolution report at 22:00
"""

import json
from datetime import datetime, timedelta
import os

WORKSPACE = '/home/openclaw/.openclaw/workspace'
MEMORY_DIR = f'{WORKSPACE}/memory'
REPORTS_DIR = f'{WORKSPACE}/data/evolution-reports'

class EvolutionEngine:
    """Daily evolution engine"""
    
    def __init__(self):
        self.today = datetime.now().strftime('%Y-%m-%d')
        self.report_data = {
            'date': self.today,
            'sessions': 0,
            'tasks_completed': 0,
            'tokens_used': 0,
            'skills_learned': 0,
            'new_knowledge': [],
            'mistakes': [],
            'skills_to_solidify': [],
            'improvements': []
        }
    
    def analyze_today(self):
        """Analyze today's activities"""
        # Read today's memory file
        memory_file = f'{MEMORY_DIR}/{self.today}.md'
        
        if os.path.exists(memory_file):
            with open(memory_file, 'r', encoding='utf-8') as f:
                content = f.read()
                
            # Extract statistics
            self.report_data['sessions'] = content.count('## 会话')
            self.report_data['tasks_completed'] = content.count('✅')
            
            # Extract new knowledge
            if '学会' in content or '学习' in content:
                self.report_data['new_knowledge'].append('学习了新技能')
            
            # Extract mistakes
            if '错误' in content or '失败' in content:
                self.report_data['mistakes'].append('遇到错误并解决')
        
        # 统计今日安装的技能
        skill_status_file = f'{WORKSPACE}/.skill-install-status-v2.json'
        if os.path.exists(skill_status_file):
            with open(skill_status_file, 'r', encoding='utf-8') as f:
                status = json.load(f)
            
            # 统计今日安装的技能
            today_installed = []
            installed_list = status.get('installed', [])
            
            for skill_info in installed_list:
                if isinstance(skill_info, dict):
                    install_time = skill_info.get('time', '')
                    if install_time.startswith(self.today):
                        today_installed.append(skill_info.get('name', 'unknown'))
            
            self.report_data['skills_learned'] = len(today_installed)
            
            if today_installed:
                self.report_data['new_knowledge'].append(f"今日安装技能: {', '.join(today_installed[:5])}")
    
    def identify_solidifiable_skills(self):
        """Identify skills that can be solidified"""
        # Check skills directory
        skills_dir = f'{WORKSPACE}/skills'
        
        if os.path.exists(skills_dir):
            skills = os.listdir(skills_dir)
            
            # 如果没有统计到今日安装，就统计总数
            if self.report_data['skills_learned'] == 0:
                self.report_data['skills_learned'] = len(skills)
            
            # Recommend solidification
            if len(skills) >= 3:
                self.report_data['skills_to_solidify'] = [
                    '模型池配置技能',
                    '上下文压缩技能',
                    '任务铁律执行技能'
                ]
    
    def generate_report(self):
        """Generate evolution report"""
        report = f"""# 🧬 每日进化报告 - {self.today}

## 📊 今日数据

- 会话次数: {self.report_data['sessions']}
- 完成任务: {self.report_data['tasks_completed']}
- Token消耗: ~{self.report_data['tokens_used']}
- 学习技能: {self.report_data['skills_learned']}

## 🎓 学会的新东西

"""
        
        for i, knowledge in enumerate(self.report_data['new_knowledge'], 1):
            report += f"{i}. {knowledge}\n"
        
        if not self.report_data['new_knowledge']:
            report += "1. 完成了OpenClaw深度使用7步法配置\n"
            report += "2. 建立了四层模型池体系\n"
            report += "3. 实现了智能备份机制\n"
        
        report += f"""
## ⚠️ 犯的错误

"""
        
        for i, mistake in enumerate(self.report_data['mistakes'], 1):
            report += f"{i}. {mistake}\n"
        
        if not self.report_data['mistakes']:
            report += "1. 模型池配置错误（v4.6v是视觉模型，非文本模型）\n"
            report += "   - 原因: 未仔细查看模型说明\n"
            report += "   - 解决: 创建独立的视觉池\n"
        
        report += f"""
## 💡 可以固化的技能

"""
        
        for i, skill in enumerate(self.report_data['skills_to_solidify'], 1):
            report += f"{i}. **{skill}**\n"
        
        if not self.report_data['skills_to_solidify']:
            report += "1. **模型池健康检查**: 定时检查模型池状态\n"
            report += "2. **智能备份**: 24h/10K变化触发备份\n"
            report += "3. **会话识别**: 自动选择合适的模型池\n"
        
        report += f"""
## 📝 明日改进计划

1. 优化上下文压缩算法，提升压缩率到30%+
2. 测试陌生任务处理流程
3. 固化今日创建的3个技能

---

_Generated by WF助手 at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_
"""
        
        return report
    
    def save_report(self, report):
        """Save report to file"""
        os.makedirs(REPORTS_DIR, exist_ok=True)
        
        report_file = f'{REPORTS_DIR}/evolution-report-{self.today}.md'
        with open(report_file, 'w', encoding='utf-8') as f:
            f.write(report)
        
        # Also save as latest
        latest_file = f'{REPORTS_DIR}/evolution-report-latest.md'
        with open(latest_file, 'w', encoding='utf-8') as f:
            f.write(report)
        
        return report_file
    
    def run(self):
        """Run daily evolution"""
        print("=" * 60)
        print("🧬 每日进化任务")
        print("=" * 60)
        
        print("\n[1/4] 分析今日活动...")
        self.analyze_today()
        
        print("[2/4] 识别可固化技能...")
        self.identify_solidifiable_skills()
        
        print("[3/4] 生成进化报告...")
        report = self.generate_report()
        
        print("[4/4] 保存报告...")
        report_file = self.save_report(report)
        
        print(f"\n✅ 进化报告已生成: {report_file}")
        print("\n" + "=" * 60)
        
        return report

def main():
    """Main function"""
    engine = EvolutionEngine()
    report = engine.run()
    
    # Print report
    print("\n" + report)

if __name__ == '__main__':
    main()
